import cv2
import numpy as np
import os
import json
import argparse
from typing import Tuple


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract PCB trace topology and attack candidate mask."
    )

    parser.add_argument(
        "--image",
        type=str,
        default=os.path.join("PCB_Dataset", "04.JPG"),
        help="Path to input PCB image."
    )

    parser.add_argument(
        "--config",
        type=str,
        default=os.path.join("configs", "hsv_trace_config.json"),
        help="Path to HSV config generated by hsv_tracker.py."
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default=os.path.join("outputs", "topology"),
        help="Directory to save topology outputs."
    )

    parser.add_argument(
        "--min_area",
        type=int,
        default=80,
        help="Minimum connected component area to keep in trace mask."
    )

    parser.add_argument(
        "--close_kernel",
        type=int,
        default=3,
        help="Kernel size for morphological closing."
    )

    parser.add_argument(
        "--open_kernel",
        type=int,
        default=3,
        help="Kernel size for morphological opening."
    )

    parser.add_argument(
        "--border_margin",
        type=int,
        default=25,
        help="Margin size for removing image border artifacts."
    )

    parser.add_argument(
        "--attack_min_area",
        type=int,
        default=150,
        help="Minimum connected component area for attack candidate mask."
    )

    parser.add_argument(
        "--attack_max_area",
        type=int,
        default=-1,
        help="Maximum connected component area for attack candidate mask. Use -1 to disable upper area filtering."
    )

    return parser.parse_args()


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def load_hsv_config(config_path: str) -> Tuple[np.ndarray, np.ndarray]:
    if not os.path.exists(config_path):
        raise FileNotFoundError(
            f"HSV config not found: {config_path}. "
            f"Please run hsv_tracker.py first and press 's' to save config."
        )

    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    lower = np.array(config["trace_hsv_lower"], dtype=np.uint8)
    upper = np.array(config["trace_hsv_upper"], dtype=np.uint8)

    return lower, upper


def remove_small_components(binary_mask: np.ndarray, min_area: int) -> np.ndarray:
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        binary_mask,
        connectivity=8
    )

    cleaned = np.zeros_like(binary_mask)

    for label_id in range(1, num_labels):
        area = stats[label_id, cv2.CC_STAT_AREA]

        if area >= min_area:
            cleaned[labels == label_id] = 255

    return cleaned


def clean_trace_mask(
    raw_mask: np.ndarray,
    min_area: int = 80,
    close_kernel: int = 3,
    open_kernel: int = 3
) -> np.ndarray:
    mask = raw_mask.copy()

    if close_kernel > 0:
        kernel_close = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (close_kernel, close_kernel)
        )
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel_close)

    if open_kernel > 0:
        kernel_open = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (open_kernel, open_kernel)
        )
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel_open)

    mask = remove_small_components(mask, min_area=min_area)

    return mask


def remove_image_border(mask: np.ndarray, margin: int = 25) -> np.ndarray:
    cleaned = mask.copy()
    h, w = cleaned.shape[:2]

    cleaned[:margin, :] = 0
    cleaned[h - margin:, :] = 0
    cleaned[:, :margin] = 0
    cleaned[:, w - margin:] = 0

    return cleaned


def filter_components_by_area(
    binary_mask: np.ndarray,
    min_area: int = 150,
    max_area: int = -1
) -> np.ndarray:
    """
    Keep connected components whose area is >= min_area.

    If max_area <= 0, upper area filtering is disabled.
    This is important for PCB images because real trace networks can form
    very large connected components.
    """
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        binary_mask,
        connectivity=8
    )

    filtered = np.zeros_like(binary_mask)

    for label_id in range(1, num_labels):
        area = stats[label_id, cv2.CC_STAT_AREA]

        if max_area <= 0:
            keep = area >= min_area
        else:
            keep = min_area <= area <= max_area

        if keep:
            filtered[labels == label_id] = 255

    return filtered


def create_attack_candidate_mask(
    trace_mask: np.ndarray,
    border_margin: int = 25,
    min_area: int = 150,
    max_area: int = -1
) -> np.ndarray:
    candidate = trace_mask.copy()

    # Remove noisy regions close to the image boundary.
    candidate = remove_image_border(candidate, margin=border_margin)

    # Remove tiny noise only.
    # Do NOT remove large components here, because PCB trace networks can be large.
    candidate = filter_components_by_area(
        candidate,
        min_area=min_area,
        max_area=max_area
    )

    return candidate


def create_overlay(
    image_bgr: np.ndarray,
    mask: np.ndarray,
    alpha: float = 0.45
) -> np.ndarray:
    overlay = image_bgr.copy()

    color_layer = np.zeros_like(image_bgr)
    color_layer[:, :, 2] = 255  # red channel in BGR

    mask_bool = mask > 0

    overlay[mask_bool] = cv2.addWeighted(
        image_bgr[mask_bool],
        1 - alpha,
        color_layer[mask_bool],
        alpha,
        0
    )

    return overlay


def create_topology_map(mask: np.ndarray) -> np.ndarray:
    topology = np.zeros_like(mask)
    topology[mask > 0] = 255
    return topology


def create_contour_debug(image_bgr: np.ndarray, mask: np.ndarray) -> np.ndarray:
    debug = image_bgr.copy()

    contours, _ = cv2.findContours(
        mask,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    cv2.drawContours(debug, contours, -1, (0, 0, 255), 2)

    return debug


def get_file_stem(path: str) -> str:
    filename = os.path.basename(path)
    stem, _ = os.path.splitext(filename)
    return stem


def save_image(path: str, image: np.ndarray):
    success = cv2.imwrite(path, image)
    if not success:
        raise IOError(f"Failed to save image: {path}")


def main():
    args = parse_args()

    ensure_dir(args.output_dir)

    image = cv2.imread(args.image)

    if image is None:
        print(f"[ERROR] Cannot read image: {args.image}")
        return

    lower_hsv, upper_hsv = load_hsv_config(args.config)

    print(f"[INFO] Loaded image: {args.image}")
    print(f"[INFO] Image shape: {image.shape}")
    print(f"[INFO] HSV lower: {lower_hsv.tolist()}")
    print(f"[INFO] HSV upper: {upper_hsv.tolist()}")

    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    raw_trace_mask = cv2.inRange(hsv, lower_hsv, upper_hsv)

    clean_mask = clean_trace_mask(
        raw_trace_mask,
        min_area=args.min_area,
        close_kernel=args.close_kernel,
        open_kernel=args.open_kernel
    )

    attack_candidate = create_attack_candidate_mask(
        clean_mask,
        border_margin=args.border_margin,
        min_area=args.attack_min_area,
        max_area=args.attack_max_area
    )

    overlay = create_overlay(image, clean_mask)
    topology = create_topology_map(clean_mask)
    contour_debug = create_contour_debug(image, clean_mask)

    attack_overlay = create_overlay(image, attack_candidate)
    attack_topology = create_topology_map(attack_candidate)
    attack_contour_debug = create_contour_debug(image, attack_candidate)

    stem = get_file_stem(args.image)

    raw_mask_path = os.path.join(args.output_dir, f"{stem}_raw_trace_mask.png")
    clean_mask_path = os.path.join(args.output_dir, f"{stem}_trace_mask.png")
    overlay_path = os.path.join(args.output_dir, f"{stem}_trace_overlay.png")
    topology_path = os.path.join(args.output_dir, f"{stem}_topology.png")
    contour_path = os.path.join(args.output_dir, f"{stem}_contours.png")

    attack_mask_path = os.path.join(args.output_dir, f"{stem}_attack_candidate_mask.png")
    attack_overlay_path = os.path.join(args.output_dir, f"{stem}_attack_candidate_overlay.png")
    attack_topology_path = os.path.join(args.output_dir, f"{stem}_attack_candidate_topology.png")
    attack_contour_path = os.path.join(args.output_dir, f"{stem}_attack_candidate_contours.png")

    save_image(raw_mask_path, raw_trace_mask)
    save_image(clean_mask_path, clean_mask)
    save_image(overlay_path, overlay)
    save_image(topology_path, topology)
    save_image(contour_path, contour_debug)

    save_image(attack_mask_path, attack_candidate)
    save_image(attack_overlay_path, attack_overlay)
    save_image(attack_topology_path, attack_topology)
    save_image(attack_contour_path, attack_contour_debug)

    print("[SUCCESS] Topology extraction completed.")
    print(f"  Raw mask:        {raw_mask_path}")
    print(f"  Clean mask:      {clean_mask_path}")
    print(f"  Overlay:         {overlay_path}")
    print(f"  Topology map:    {topology_path}")
    print(f"  Contours:        {contour_path}")
    print(f"  Attack mask:     {attack_mask_path}")
    print(f"  Attack overlay:  {attack_overlay_path}")
    print(f"  Attack topology: {attack_topology_path}")
    print(f"  Attack contours: {attack_contour_path}")


if __name__ == "__main__":
    main()